### ISSUE TITLE
Manylinux wheels for x86-64

### ISSUE THREAD

**Issue by stefan6419846** [ariebovenberg/whenever#142]
Trying to download/install the package using `pip download --no-deps whenever` with the `wheel` package installed will download the source distribution and try to build it on a regular x86_64 architecture. I would have expected that this common architecture would already be supported out of the box in the form of binary wheels.

The system is an up-to-date Ubuntu 22.04 running Python 3.10.12 with `wheel==0.40.0`, `setuptools==59.6.0` and `pip==22.0.2`.

**Comment by ariebovenberg** [comment]
Hi @stefan6419846, thanks for posting. You're right, x86_64 should of course have a wheel! It seems I've made a mistake in configuring matric in github actions. The way github actions works, the `musllinux-x86_64` entry _overwrites_ the existing matrix entry 🤔 

```
        os: [windows, macos, linux]
        target: [x86_64, aarch64]
        include:
          # additional linux targets
          - os: linux
            target: x86
          - os: linux
            target: armv7
          - os: linux
            target: ppc64le
          - os: linux
            target: s390x

          # musl targets
          - os: linux
            target: x86_64
            manylinux: musllinux_1_2
          - os: linux
            target: x86
            manylinux: musllinux_1_2
          - os: linux
            target: aarch64
            manylinux: musllinux_1_2
          - os: linux
            target: armv7
            manylinux: musllinux_1_2

          - os: windows
            python-architecture: x86
            target: x86

        exclude:
          - os: windows
            target: aarch64
```
